### PR TITLE
feat: enhancement and minor optimization in Makefile 

### PR DESCRIPTION
**Pull request by Kushal-kothari**
Created a function that builds rpm packages that helps in handling duplicate code and partly fixes the issue of optimization . #19

### CODE REVIEW

**Comment by Kushal-kothari** [comment]
@membphis

**Comment by Kushal-kothari** [comment]
This is my first contribution here. Can someone with write access(maintainer) approve the workflow whenever they'll saw this? The packages are running on my machine!

**Comment by membphis** [comment]
@spacewander @nic-chen do you know the reason?

**Comment by spacewander** [comment]
The version in `make package type=rpm app=apisix-openresty version=${BUILD_APISIX_OR_VERSION}` is not passed through in this PR.

**Comment by nic-chen** [comment]
@Kushal-kothari 
I think you could do some debug in CI.

**Comment by Kushal-kothari** [comment]
> The version in `make package type=rpm app=apisix-openresty version=${BUILD_APISIX_OR_VERSION}` is not passed through in this PR.

Sorry. I didn't understand what changes should I implement to pass the failing test? Can you please help me point down where I should make the changes? The packages have been successfully installed on my machine still Idk why my test is failing.
Screenshot from 2021-07-26 20-56-44

> I think you could do some debug in CI.

All the 3 packages are successfully running on my machine. I am still struggling to figure out why the test failed :( .What exactly can I do? @nic-chen 
[PS: I am new to the community so spare my noob questions as I am unaware of many terms]

**Comment by spacewander** [comment]
Yes, but the package doesn't have the version info. We need to pass the version as part of the build argument:
https://github.com/api7/apisix-build-tools/blob/f6683f89c582bc6d819af95a1ea2cb49ce19d2d8/build-apisix-openresty.sh#L66
https://github.com/api7/apisix-build-tools/blob/f6683f89c582bc6d819af95a1ea2cb49ce19d2d8/build-apisix-openresty.sh#L74

You might see the value of `-DAPISIX_OPENRESTY_VER=0.0.0` via `nginx -V`. The `APISIX_OPENRESTY_VER` should be the specific version.

**Comment by Kushal-kothari** [comment]
@spacewander I pushed the commit wherein I passed the version info. Still, the last test failed.

**Comment by spacewander** [comment]
The version still hasn't been passed. See the output in the "build apisix-openresty rpm" section of the CI log:
```
cc -c -I/tmp/tmp.01gcBodzze/openresty-1.19.3.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -I/tmp/tmp.01gcBodzze/openresty-1.19.3.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -DAPISIX_OPENRESTY_VER=0.0.0
```

The `-DAPISIX_OPENRESTY_VER=` is still `0.0.0`.

**Review by spacewander — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
