### PR TITLE
feat: support dashboard systemd service unit

### PR DESCRIPTION
**Pull request by bzp2010**

### CODE REVIEW

**Review by nic-chen — COMMENTED** [review]
@bzp2010  please fix CI

**Comment by bzp2010** [comment]
ping @nic-chen

**Comment by nic-chen** [comment]
@bzp2010  need test cases for start and stop by systemctl

**Comment by bzp2010** [comment]
> @bzp2010 need test cases for start and stop by systemctl

Hi, @nic-chen.

I've read the code. The current test environment is based on docker, but it's not easy to use systemd in the container. At the same time, I haven't seen the relevant test code of APISIX. Are there any cases for reference?

**Comment by nic-chen** [comment]
@bzp2010 

> I've read the code. The current test environment is based on docker, but it's not easy to use systemd in the container. 
could we replace [this line](https://github.com/api7/apisix-build-tools/blob/master/.github/workflows/package-apisix-dashboard-rpm-el7.yml#L80) to `systemctl start apisix-dashboard`?

> At the same time, I haven't seen the relevant test code of APISIX. Are there any cases for reference?

APISIX is very different from the dashboard. Even without systemd, APISIX can be started or stopped under any path, but dashboard has path dependency.

**Comment by bzp2010** [comment]
@nic-chen 
> could we replace [this line](https://github.com/api7/apisix-build-tools/blob/master/.github/workflows/package-apisix-dashboard-rpm-el7.yml#L80) to `systemctl start apisix-dashboard`?

We're afraid we can't do that, systemd may not be available in Docker containers, or there may be high requirements for the environment. I will think of some other ways.

**Comment by bzp2010** [comment]
Hi, @nic-chen. I have added tests for systemd that use this approach. I used the systemd mode of the RedHat Podman container program and started a CentOS7 container in which to run the tests. PTAL, thanks.

**Review by juzhiyuan — APPROVED** [review]

**Comment by bzp2010** [comment]
ping @imjoey @gxthrj APISIX Dashboard version 2.10 release depends on this PR build RPM package, please help to review it, thanks.

**Review by imjoey — APPROVED** [review]
/lgtm

**Pull request merged**
